# Generated by Django 5.2.5 on 2025-08-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='aiAnalysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='match',
            name='aiExplanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='aiScore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='detailedScores',
            field=models.JSONField(default=dict),
        ),
    ]
