# Generated by Django 5.0.7 on 2025-08-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match_aianalysis_match_aiexplanation_match_aiscore_and_more'),
    ]

    operations = [
        # First, delete all matches that have null professor fields (project matches)
        migrations.RunSQL(
            "DELETE FROM matches WHERE professor_id IS NULL;",
            reverse_sql=""
        ),
        
        # Remove the project field from Match model
        migrations.RemoveField(
            model_name='match',
            name='project',
        ),
        
        # Remove the matchType field from Match model
        migrations.RemoveField(
            model_name='match',
            name='matchType',
        ),
        
        # Make professor field non-nullable
        migrations.AlterField(
            model_name='match',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.professorprofile'),
        ),
        
        # Delete the ResearchProject model
        migrations.DeleteModel(
            name='ResearchProject',
        ),
    ]
