# Generated by Django 5.2.5 on 2025-08-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_research_project_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='hoursPerWeek',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
